<?php
namespace App\Http\Controllers\Api\Owner;
use App\Http\Controllers\Controller; use App\Models\RawMaterial; use App\Services\OwnerAutomationService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request;
class RawMaterialController extends Controller {
  public function __construct(protected OwnerAutomationService $automation) {}
  public function index(Request $r): JsonResponse { return response()->json(RawMaterial::with('supplier:id,name')->where('shop_id',$r->user()->shop_id)->latest('id')->get()); }
  public function store(Request $r): JsonResponse { $v=$r->validate(['supplier_id'=>'nullable|integer|exists:suppliers,id','material_name'=>'required|string|max:150','category'=>'nullable|string|max:100','color'=>'nullable|string|max:100','unit'=>'nullable|string|max:50','stock_quantity'=>'nullable|numeric|min:0','reorder_level'=>'nullable|numeric|min:0','cost_per_unit'=>'nullable|numeric|min:0','last_restocked_at'=>'nullable|date','status'=>'nullable|string|max:50','notes'=>'nullable|string']); $m=RawMaterial::create(array_merge($v,['shop_id'=>$r->user()->shop_id,'unit'=>$v['unit']??'pcs','status'=>$v['status']??'in_stock'])); $this->automation->syncLowStockAlerts($r->user()->shop_id); return response()->json($m->load('supplier:id,name'),201);} 
  public function update(Request $r,RawMaterial $rawMaterial): JsonResponse { abort_unless($rawMaterial->shop_id===$r->user()->shop_id,403); $v=$r->validate(['supplier_id'=>'nullable|integer|exists:suppliers,id','material_name'=>'sometimes|required|string|max:150','category'=>'nullable|string|max:100','color'=>'nullable|string|max:100','unit'=>'nullable|string|max:50','stock_quantity'=>'nullable|numeric|min:0','reorder_level'=>'nullable|numeric|min:0','cost_per_unit'=>'nullable|numeric|min:0','last_restocked_at'=>'nullable|date','status'=>'nullable|string|max:50','notes'=>'nullable|string']); $rawMaterial->update($v); $this->automation->syncLowStockAlerts($r->user()->shop_id); return response()->json($rawMaterial->fresh()->load('supplier:id,name')); }
}
